trigger:
- main

pool:
  name: iman

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --Configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
