trigger:
- main

pool:
  name: iman

steps:
- task: UseDotNet@2
  displayName: 'Use .NET sdk 8.x'
  inputs:
    packageType: sdk
    version: '8.x'
- task: Npm@1
  displayName: 'Run npm install'